const types = {
    //users module
    LOAD_USERS: 'LOAD_USERS',
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',


    //roles module
    LOAD_ROLES: 'LOAD_ROLES',
    ADD_ROLE_SUCCESS:'ADD_ROLE_SUCCESS',
    DELETE_ROLE_SUCCESS: 'DELETE_ROLE_SUCCESS',
    UPDATE_ROLE_SUCCESS: 'UPDATE_ROLE_SUCCESS',


    //search component
    

}

export default types;