const types = {
    //users module
    LOAD_USERS: 'LOAD_USERS',
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',


    //roles module
    LOAD_ROLES: 'LOAD_ROLES',
    ADD_ROLE_SUCCESS:'ADD_ROLE_SUCCESS',
    DELETE_ROLE_SUCCESS: 'DELETE_ROLE_SUCCESS',
    UPDATE_ROLE_SUCCESS: 'UPDATE_ROLE_SUCCESS',

    // interests module
    LOAD_INTERESTS: 'LOAD_INTERESTS',
    ADD_INTEREST_SUCCESS:'ADD_INTERESTS_SUCCESS',
    DELETE_INTEREST_SUCCESS: 'DELETE_INTERESTS_SUCCESS',
    UPDATE_INTEREST_SUCCESS: 'UPDATE_INTERESTS_SUCCESS',

    //services module
    LOAD_SERVICES: 'LOAD_SERVICES',
    ADD_SERVICES_SUCCESS:'ADD_SERVICES_SUCCESS',
    DELETE_SERVICES_SUCCESS: 'DELETE_SERVICES_SUCCESS',
    UPDATE_SERVICES_SUCCESS: 'UPDATE_SERVICES_SUCCESS',

    //state services
    LOAD_STATE_SERVICES: 'LOAD_STATE_SERVICES',
    ADD_STATE_SERVICES_SUCCESS:'ADD_STATE_SERVICES_SUCCESS',
    DELETE_STATE_SERVICES_SUCCESS: 'DELETE_STATE_SERVICES_SUCCESS',
    UPDATE_STATE_SERVICES_SUCCESS: 'UPDATE_STATE_SERVICES_SUCCESS',

    // user services
    LOAD_USER_SERVICES: 'LOAD_USER_SERVICES',
    ADD_USER_SERVICES_SUCCESS:'ADD_USER_SERVICES_SUCCESS',
    DELETE_USER_SERVICES_SUCCESS: 'DELETE_USER_SERVICES_SUCCESS',
    UPDATE_USER_SERVICES_SUCCESS: 'UPDATE_USER_SERVICES_SUCCESS',

    // mactchs module



    //search component
    LOAD_MATCHS:  'LOAD_MATCHS',
    ADD_MATCH_SUCCESS:'ADD_MATCH_SUCCESS',
    DELETE_MATCH_SUCCESS: 'DELETE_MATCH_SUCCESS',
    UPDATE_MATCH_SUCCESS: 'UPDATE_MATCH_SUCCESS',
    

}

export default types;