const types = {
    //users module
    LOAD_USERS: 'LOAD_USERS',
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS'
}

export default types;